[toolchain]
package_manager = "yarn"
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vigia_protocol = "GYD8shoAEN7YabduYsM6SQgjWq5jp9assruMFV9FGJMc"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
